### ISSUE TITLE
建议反馈

### ISSUE THREAD

**Issue by StarHonest** [TeamMoegMC/The-Winter-Rescue#1]
整合包beta0.2版本中意志坚定模组与WaterSource模组的饮水贴图重合，且两个模组饮水不互通，使用任务书里的水袋则意志坚定中的饮水无法满足，而shift+右键饮水不能补充WaterSource中的口渴值。只有用玻璃瓶取生水才能满足二者。但问题就是饮用生水后WaterSource的口渴buff持续时间一分半过长，且口渴值下降速度过快

**Comment by StarHonest** [comment]
新建一个档后发现只有WaterSource的饮水了，说明二者同时出现可能是bug需要修改

**Comment by yuesha-yc** [comment]
请确保更新后使用的config是最新版本，因为我已经明确关闭了Survive模组的饮水功能。
